### ISSUE TITLE
Rotated bounding boxes

### ISSUE THREAD

**Issue by ogencoglu** [Smirkey/powerboxes#28]
Thanks for the work!

If I understood correctly, this library works only on axis-aligned bounding boxes. Any plans on supporting rotated bounding boxes?

**Comment by Smirkey** [comment]
Hi ! 
Yes I have this in mind too :) I'll add it in the future

**Comment by ogencoglu** [comment]
Great! Especially fitting a rotated box to an arbitrarily shaped polygon would be super useful:
- one that maximizes Intersection over Union
- one that minimizes Hausdorff distance between contours
- one that minimizes the bbox area while encapsulating the whole polygon (e.g. standard bbox fit in opencv)

**Comment by Smirkey** [comment]
Ok

**Comment by Smirkey** [comment]
Hi :)
Some support to rotated bounding boxes was added with #33 #37 and #43 

> fitting a rotated box to an arbitrarily shaped polygon would be super useful:
Regarding this, I'm not sure to add it in near future, since it involves taking polygons as input and it's not what I envisioned for the lib

**Comment by ogencoglu** [comment]
Thanks!
