### ISSUE TITLE
Use views instead of owned arrays where possible

### ISSUE THREAD

**Issue by BTOdell** [Smirkey/powerboxes#51]
Many of the functions in this library require owned arrays to be passed: https://github.com/Smirkey/powerboxes/blob/main/powerboxesrs/src/nms.rs#L32

The algorithm eventually makes a copy of the data anyway, so it would be more efficient to only require views to be passed as input.

**Comment by Smirkey** [comment]
Some very good advice thanks :)
I will look into it

**Comment by BTOdell** [comment]
I applied these recommendations (along with some others) to my own fork: https://github.com/Smirkey/powerboxes/pull/52

**Comment by Smirkey** [comment]
great thanks !!

**Comment by Smirkey** [comment]
solved by #53
